services:
  synology-photos-lib:
    image:
      synology-photos-lib:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
