### GET Info Https
GET https://{{host}}/photo/webapi/entry.cgi
    ?api=SYNO.API.Info&version=1&method=query&query=SYNO.FotoTeam.Browse.Item

### GET Info Http
GET http://{{host}}/photo/webapi/entry.cgi
    ?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth,SYNO.FotoTeam.Browse.Person

### Login Http with otp
GET http://{{host}}/photo/webapi/entry.cgi
    ?api=SYNO.API.Auth&version=7&method=login&
    account={{username}}&passwd={{password}}&otp_code={{otp}}&
    enable_device_token=yes&device_name={{deviceName}}

### Login Http with deviceId
GET http://{{host}}/photo/webapi/entry.cgi
    ?api=SYNO.API.Auth&version=7&method=login&
    account={{username}}&passwd={{password}}&device_id={{deviceId}}

###